# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$azure\
$kubernetes\
$helm\
$vagrant\
$nodejs\
$dotnet\
$container
$character"""

# Inserts a blank line between shell prompts
add_newline = false

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[✗](bold red)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
style = 'bold fg:#F05133'

[kubernetes]
disabled = false
format = '[\[☸  $context \($namespace\)\]](dimmed purple) '

[username]
disabled = true
show_always = true

[azure]
disabled = true
